// Generated by Wrangler on Sat May 18 2024 10:10:58 GMT+0300 (GMT+03:00)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	HELLO: string;
	RATE_LIMITER: any;
}
